In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
a = np.array([[1, 2, 3]])

In [15]:
a * 2

array([[2, 4, 6]])

In [17]:
b = np.array([[1, 2, 3]])
a * b

array([[1, 4, 9]])

In [18]:
X = np.array([[1, 2, 3]])
W = np.random.randn(3, 3)
W @ W


array([[ 1.26180204, -0.15705855,  0.00502368],
       [ 2.13800948,  2.8705907 , -1.64429655],
       [ 1.92931701, -0.12928968,  1.32044158]])